version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  nextjs:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/meditation
    depends_on:
      - mongodb
